@startuml
hide empty members
set namespaceSeparator none

skinparam class {
        BackgroundColor PaleGreen
        ArrowColor RoyalBlue
        BorderColor DimGray
}

class  ApiResponse {
         
         - code  

         - message  

         - type  
}

class  Category {
         
         - id  

         - name  
}

class  Order {
         
         - complete  

         - id  

         - petId  

         - quantity  

         - shipDate  

         - status  
}

class  Pet {
         
         - category  

         - id  

         - name  

         - photoUrls  

         - status  

         - tags  
}

class  Tag {
         
         - id  

         - name  
}

class  User {
         
         - email  

         - firstName  

         - id  

         - lastName  

         - password  

         - phone  

         - userStatus  

         - username  
}




note as N1
  Name: <b><color:royalBlue>Swagger Petstore</color>
  Version: <b><color:royalBlue>1.0.0</color>
end note
@enduml