[server]
address="0.0.0.0"
port=80  #server default  listening on 80  
dir="./examples/simple-config/server/modules"



[database]
type="mysql"
host="127.0.0.1"
port=3306
database="test"
username="root"
password="root"

[generator]
# compile code to dist directory,default ./dist  
out_dir="./dist" 
# server generate template  ,such as `spring-boot`,netcore `abp`,rust `rocket`
server="spring-boot"
client="ng-alain"

[swagger]
swagger="2.0"
[swagger.info]
title= "Swagger Petstore"
version= "1.0.0"
termsOfService= "http://swagger.io/terms/"
